pom.xml, src/main/java/com/ocient/cli/CLI.java
=> Remove timestamp from date printed by CLI

src/main/proto/ClientWireProtocol.proto
=> Add LOCAL_KILL/CANCEL_QUERY to jdbc wire proto

src/main/java/com/ocient/jdbc/SQLStates.java
https://jira.ocient.com:8443/browse/DB-9930
=> DB-9930: Add TRANSLATION_NOT_FOUND

pom.xml, src/main/proto/PlanProtocol.proto, userdoc/release_notes.adoc
Scp'ed the jar file in ocient-archive server.
Will update the version# in xgjdbc/Makefile in db branch in a separate PR.
=> Added lhs/rhs type string in filter clause

pom.xml, src/main/proto/PlanProtocol.proto, userdoc/release_notes.adoc
scp'ed the jar file to ocient-archive.
Also updated the version to 1.19 in xgjdbc/Makefile in xgsrc.
=> Added pfactor for shuffle operator

src/main/java/com/ocient/jdbc/SQLStates.java
https://jira.ocient.com:8443/browse/DB-9712
=> WIP: DB-9712: Add TRANSLATION_ALREADY_EXISTS

pom.xml, src/main/java/com/ocient/jdbc/SQLStates.java, userdoc/release_notes.adoc
=> empty mlmodel set is now error

pom.xml, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-11722
=> DB-11722: Release v1.32

src/main/java/com/ocient/jdbc/SQLStates.java
https://jira.ocient.com:8443/browse/DB-11091
=> DB-11091: Update SQL States

.gitlab-ci.yml
Builds jar and sends to ocient-archive
=> Jdbc internal autodeploy

src/main/java/com/ocient/jdbc/XGConnection.java
https://jira.ocient.com:8443/browse/DB-12725
=> Fix forced infinite loop.

src/main/java/com/ocient/jdbc/XGStatement.java
https://jira.ocient.com:8443/browse/DB-12725
Fix for jdbc driver not reconnecting.
Now you can connect. Then do something like `pkill -9 rolehostd` . Then relaunch the server. The client will try to reconnect every time you type a command. You still have to wait for the server to come back up though. Be patient.
=> [DB-12725] fix not reconnect

src/main/java/com/ocient/cli/CLI.java
=> fix jdbc source file

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-12845
Ugly diff, but really we are just adding an 
`if(outputfile){
print to output file;
}
else {
old code;
}
`
=> [DB-12845] output_next_query for explain and others

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-12998
Move export translation into result set. One cell. @pyusimocient  will bump the version on the xgsrc side along with his fix for the export table and export translation tests.
=> [DB-12998] move export translation into result set

pom.xml, src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-13243
export translation wasn't closing its result set.
=> exporttranslation close result set

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGResultSet.java, userdoc/release_notes.adoc
We do not need to fetch the server version every time we reconnect.
=> remove unecessary server version fetches

pom.xml, src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
=> DESCRIBE TABLE uses SQL type names for arrays

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-13805
Alright I think this is what we want. Right before we reconnect, check the previously connected port and ip. If we cannot connect to it, then it's likely we just killed it with a query. Then don't resend. Otherwise, resend.
=> Fix reconnect logic

pom.xml, src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
This was something I added to aid with debugging and was not intended to be merged with #81 !
=> Don't print stack trace when select queries complete exceptionally

pom.xml, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
Improvements as a part of the workload management feature
=> Properly handle column nullability for LIST ALL COMPLETED QUERIES

pom.xml, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-14051
=> [DB-14051] jdbc syntax spacing

src/main/java/com/ocient/jdbc/XGStatement.java
DB-13546: Implement completed queries virtual operator
=> Fixed incorrect column names in cols2Types mapping

pom.xml, userdoc/release_notes.adoc
1.66 did not get redeployed with 4547bdf8b6469180fdae22ce6e57e78eef03b794 so I need a version bump
=> Bump jdbc version to 1.67

pom.xml, src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-14209
=> [DB-14209] fix describe view truncation

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGResultSet.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-14634
See this ticket for explanation.
Also removes some duplicate code. I don't know how this happened, but we don't need to duplicate those pso blocks.
=> fix race condition between adding threads and starting them

pom.xml, src/main/java/com/ocient/jdbc/SQLStates.java
XGSRC companion for sqlstate change https://github.com/Xeograph/xgsrc/pull/15242
Pom looks like I changed a lot, but I just disabled plugin sorting and swapped the order of the two plugins that matter.
=> Updated column not found message + probably fix auto-deploy task

src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-15218
=> [DB-15218] fix set schema

pom.xml, src/main/java/com/ocient/jdbc/SQLStates.java
See https://github.com/Xeograph/xgsrc/pull/15414
=> Add SQLState for LUP decomposition error

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
Will put this together with Ryan's matrix state additions for 1.78
=> add more logging and fix schema on copied fethserverversion connection

pom.xml, src/main/java/com/ocient/cli/FastStringTokenizer.java, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/SQLStates.java, userdoc/release_notes.adoc
Fixing the rest of the OWASP bugs barring one.
=> more owasp bug fixes

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGDatabaseMetaData.java, userdoc/release_notes.adoc
fix for some xgdata functions that I broke in my OWASp fixes.
https://jira.ocient.com:8443/browse/DB-15472
=> small java change

src/main/java/com/ocient/jdbc/ThreadFormatter.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-15571
=> add millisecond timing

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGPreparedStatement.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-15611
=> add call to end cache threads

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGDatabaseMetaData.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-15780
I renamed the "driverVersion" to protocolVersion to avoid confusion.
=> jdbc send driver version to server on clienthandshake

src/main/java/com/ocient/jdbc/JDBCDriver.java, userdoc/release_notes.adoc
https://jira.ocient.com:8443/browse/DB-16071
=> [DB-16071] fix setschema not working on dirver properties

src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16204
=> [DB-16204] fix CLI performance on/off afftering timing setting.

pom.xml, src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
adding new ddl support for quarantining segments
corresponding xgsrc pr: https://github.com/Xeograph/xgsrc/pull/16461
=> add quarantine keyword

src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16251
=> fix CLI force external

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGStatement.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
Corresponding xgsrc PR:
https://github.com/Xeograph/xgsrc/pull/16486
=> [DB-16200] Improve explains by making JSON default and adding debug option

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGResultSet.java, src/main/java/com/ocient/jdbc/XGStatement.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16081
=> [DB-16081] result set support + cache limit warning

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16474
=> [DB-16474] jdbc driver session ID

src/main/java/com/ocient/jdbc/XGConnection.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16566
=> [DB-16566] fix a bad log

src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16595
=> [DB-16595] fix a bad log message

pom.xml, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16396
=> [DB-16396] update project to use versions plugin

src/main/java/com/ocient/jdbc/JDBCDriver.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-15939
=> [DB-15939] jdbc defaults to unverified on TLS connections

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGPreparedStatement.java, src/main/java/com/ocient/jdbc/XGResultSet.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-16527
=> [DB-16527] use daemon threads for background tasks

pom.xml, spotbugs-exclude.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGResultSet.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
Two tickets:
https://ocient.atlassian.net/browse/DB-16620
https://ocient.atlassian.net/browse/DB-16791
=> [DB-16620] fix redirection + connection pooling

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://github.com/Xeograph/xgsrc/pull/17294
=> Add xgjdbc support for setting pso seed

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
DB pr is here https://github.com/Xeograph/xgsrc/pull/17294
=> DB-14669 add auto to set PSO seed

src/main/java/com/ocient/cli/CLI.java, userdoc/release_notes.adoc
(for reliably killing queries during optimization)
=> [DB-16127] Add support for sleep_in_optimizer

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGResultSet.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17148
=> fix timeoutmillis again

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17263
=> fix the hash code for connections

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
=> DB-17242 change concurrency to parallelism

src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
Also changes the method / var names to be less confusing
=> DB-17242 change driver property name from concurrency to parallelism

pom.xml, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17360
=> [DB-17360] have set schema handle caps

src/main/java/com/ocient/jdbc/XGRegexUtils.java
=> forgot to commit this

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGConnection.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17794
=> Remove extraneous stack trace prints from jdbc driver

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17914
https://ocient.atlassian.net/browse/DB-17915
=> fix connection resetting parameters

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-17875
=> [DB-17875] sso handshake support 

pom.xml, src/main/java/com/ocient/cli/CLI.java, src/main/java/com/ocient/jdbc/XGDatabaseMetaData.java, src/main/java/com/ocient/jdbc/XGStatement.java, userdoc/release_notes.adoc
1. stop source command on error: https://ocient.atlassian.net/browse/DB-17692 (CLI)
2. jdbc get client version: https://ocient.atlassian.net/browse/DB-18038 
3. output next query append: https://ocient.atlassian.net/browse/DB-18052
=> jdbc driver feature requests

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGStatement.java, src/main/proto/ClientWireProtocol.proto, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-18050
https://ocient.atlassian.net/browse/DB-18137
=> jdbc explicit sso handshake support

pom.xml, src/main/java/com/ocient/jdbc/XGConnection.java, src/main/java/com/ocient/jdbc/XGResultSet.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-18597
=> improve result set fetching performance

pom.xml, src/main/java/com/ocient/jdbc/JDBCDriver.java, src/main/java/com/ocient/jdbc/XGConnection.java, userdoc/release_notes.adoc
https://ocient.atlassian.net/browse/DB-18900
=> Fix connection pooling regarding setSchema
